# Generated by Django 5.2.15 on 2026-06-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер текста (1, 2 или 3)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок текста')),
                ('text_content', models.TextField(verbose_name='Текст статьи (HTML)')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста (например, Cambridge 18 - Test 1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(verbose_name='Инструкция (например, Write NO MORE THAN TWO WORDS)')),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE_NOT_GIVEN', 'True/False/Not Given'), ('FILL_GAPS', 'Sentence Completion / Fill Gaps'), ('MATCHING_HEADINGS', 'Matching Headings')], max_length=30)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='materials.passage')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер вопроса (например, 1, 2, 14)')),
                ('text', models.TextField(verbose_name='Текст вопроса (может содержать контент до/после поля ввода)')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ (для проверки, регистр не важен)')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Варианты ответов (если есть)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='materials.questiongroup')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='materials.readingtest'),
        ),
    ]
