# Generated by Django 5.2.15 on 2026-06-28 06:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.AddField(
            model_name='readingtest',
            name='template_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Например: tests/olive_oil.html', max_length=255, verbose_name='Путь к HTML файлу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readingtest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название теста'),
        ),
        migrations.CreateModel(
            name='ReadingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('band', models.FloatField()),
                ('time_spent', models.CharField(max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.readingtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Passage',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
    ]
