# Generated by Django 5.2.15 on 2026-06-28 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ieltsuser_has_result_ieltsuser_want_result'),
        ('materials', '0002_remove_questiongroup_passage_remove_question_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ieltsuser'),
        ),
    ]
