# Generated by Django 5.2.15 on 2026-07-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_listeningtest_listeningresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu sarlavhasi')),
                ('icon', models.CharField(default='fa-seedling', help_text='FontAwesome klass nomi, masalan: fa-seedling, fa-graduation-cap', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name="Inglizcha so'z")),
                ('translation', models.TextField(verbose_name="Tushuntirish yoki tarjimasi (O'zbek tilida)")),
                ('example', models.TextField(verbose_name='Gapda ishlatilishi (Example)')),
                ('band', models.CharField(default='Band 7.0+', max_length=10, verbose_name='IELTS Band darajasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='materials.vocabularycategory')),
            ],
        ),
    ]
