# Generated by Django 5.2.15 on 2026-06-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ieltsuser_has_result_ieltsuser_want_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltsuser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
