# Generated by Django 5.2.15 on 2026-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ieltsuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltsuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
