# Generated by Django 5.2.15 on 2026-07-03 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_ieltsuser_has_result_ieltsuser_challenges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Task Title')),
                ('task_type', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('vocabulary', 'Vocabulary')], default='reading', max_length=20)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Task Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Task',
                'verbose_name_plural': 'Daily Tasks',
                'ordering': ['is_completed', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MockResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_score', models.FloatField(default=0.0)),
                ('reading_score', models.FloatField(default=0.0)),
                ('writing_score', models.FloatField(default=0.0)),
                ('speaking_score', models.FloatField(default=0.0)),
                ('overall_band', models.FloatField(default=0.0, verbose_name='Overall Band')),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Result',
                'verbose_name_plural': 'Mock Results',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=1, verbose_name='Current Daily Streak')),
                ('longest_streak', models.PositiveIntegerField(default=1, verbose_name='Longest Daily Streak')),
                ('last_activity_date', models.DateField(auto_now=True, verbose_name='Last Active Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
            },
        ),
    ]
